image: Visual Studio 2015

platform:
  - x86
  - x64

configuration: Release

build_script:
  - if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015
  - if "%platform%"=="x64" set CMAKE_GENERATOR_NAME=Visual Studio 14 2015 Win64
  - cmake -H. -B_build -G "%CMAKE_GENERATOR_NAME%"
  - cmake --build _build --config %configuration%
